config/routes.rb
Rails.application.routes.draw do
  get 'signup', to: 'users#new', as: 'signup'
get 'login', to: 'sessions#new', as: 'login'
get 'logout', to: 'sessions#destroy', as: 'logout'

# match('users/:id', {:via => :post, :to => 'tags#create'})

resources :users
resources :sessions

resources :photos do
  resources :tags
end


resources :users do
  resources :photos
end

root :to => 'users#index'




end

app/models/photo.rb
class Photo < ActiveRecord::Base
  has_attached_file :image, :styles => { :large => "700x700", :medium => "500x500", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  has_many :tags
  has_many :users, through: :tags

end

app/models/tag.rb
class Tag < ActiveRecord::Base

  belongs_to :photo
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :tags
  has_many :photos, through: :tags
  validates_uniqueness_of :email
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def authorize
    redirect_to login_url, alert: "Not authorized" if current_user.nil?
  end

  def logged_in?
    redirect_to user_photos_path(current_user) if current_user
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
    user_id = request.url.split("/")[4]
    @user = User.find_by_id(user_id)
  end
  def new
    @photo = Photo.new
    user_id = request.url.split("/")[4]
    @user = User.find_by_id(user_id)
    # @tag = Tag.new
  end

  def create
    user_id = request.url.split("/")[4]
    @user = User.find_by_id(user_id)
    @photo = Photo.new(photo_params)
    # current_user.photos << @photo
    if @photo.save
      # session[:photo_id] = @photo.id
      redirect_to root_path notice: "thank you for signing up!"
    else
      render "new"
    end
  end

  def show
  end

  def update
    @photo = Photo.find(params[:id])
    @user = User.find(params[:user_id])

    # @tag = Tag.create(:user_id => @user.id, :photo_id => @photo.id)
    # if @tag.valid?
    #   flash[:notice] = "Tags were saved"
    #   redirect_to root_path
    # else
    #   redirect_to user_path
    # end
  end


private
  def photo_params
    params.require(:photo).permit(:image, :user_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_filter :logged_in?, only: [:new]

  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to users_path, notice: "logged in!"
    else
      flash.now.alert = "email or password is invalid"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to new_user_path, notice: "logged out"
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    user_id = request.url.split("/")[4]
    @user = User.find_by_id(user_id)
  end
  def new
    @photo = Photo.find_by_id(params[:photo_id])
    @tag = Tag.new
    # user_id = request.url.split("/")[4]
    @user = User.find_by_id(current_user)
  end

  def create
    @user = User.find(params[:tag][:user_id])
    @photo = Photo.find(params[:photo_id])
    @tag = Tag.create(tag_params)
    if @tag.valid?
      flash[:notice] = "Tags were saved"
      redirect_to root_path
    else
      redirect_to user_path
    end
  end

  def show
  end


private
  def tag_params
    params.require(:tag).permit(:user_id, :photo_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    if current_user

    else
      redirect_to signup_path
    end
  end
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path notice: "thank you for signing up!"
    else
      render "new"
    end
  end

  def show
    @photos = current_user.photos
    @user = User.find(current_user)
    @users = User.all
    # @tag = Tag.new
    @tags = Tag.all
  end

  def update

  end


private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% object.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PhotoShare</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
  <div id="notice" style="background: red; color: white; text-align:center;">
  <%= flash[:alert] %>
  </div>
  <div id="alert" style="background: green; color: white; text-align:center;">
  <%= flash[:notice] %>
</div>
  <% if current_user %>
    <li>Logged in as <%= current_user.email %>.</li>
    <li><%= link_to "Log Out", logout_path %></li>
      <% else %>
    <li><%= link_to "Sign Up", signup_path %></li> <li>or</li>
    <li><%= link_to "Log In", login_path %></li>
      <% end %>

<%= yield %>

</div>

</body>
</html>

app/views/photos/_form.html.erb
<%= form_for [@user, @photo], :html => { :multipart => true } do |f| %>
  <p>
    <%= hidden_field_tag "photo[user_id]", @user.id %>
    <%= f.file_field :image %>
  </p>
  <p><%= f.submit "Submit", :class => "btn btn-warning btn-xs" %></p>
<% end %>

app/views/photos/index.html.erb
<h1>Index</h1>


<ul>
  <% @user.photos.each do |photo| %>
    <div style="text-align:center">
      <p ><%= image_tag photo.image.url(:medium) %></p>


  <% end %>
</br>
    </div>
      <% end %>


<p><%= link_to "Add a new photo", new_user_photo_path(current_user) %>

app/views/photos/new.html.erb
<h1>Add New Photo</h1>

<%= render "form" %>

app/views/tags/index.html.erb
<h1>Photos i'm tagged in</h1>

<% Photo.all.each do |photo| %>
  <% if photo.tags.user_id == @user.id %>

  <div class="grey">
    <p><%=link_to image_tag(photo.image.url(:medium)), new_photo_tag_path(photo) %></p>
  </div>

  <% end %>
<% end %>

app/views/tags/new.html.erb
<%= image_tag @photo.image.url(:medium) %>


<%= form_for([@photo, @tag]) do |f| %>
      <%= hidden_field_tag "tag[user_id]", nil %>
      <%= hidden_field_tag "tag[photo_id]", @photo.id %>
      <% User.all.each do |u| %>

        <%= check_box_tag "tag[user_id]", u.id %>
        <%= u.email %><br>
      <% end %>
      <%= f.submit 'tag' %>
    <% end %>


<p><%= link_to "Add a new photo", new_user_photo_path(current_user) %></p>

app/views/tags/show.html.erb
<h1>Photos i'm tagged in</h1>

<% Photo.all.each do |photo| %>
  <% if photo.tags.user_id == @user.id %>

  <div class="grey">
    <p><%=link_to image_tag(photo.image.url(:medium)), new_photo_tag_path(photo) %></p>



  </div>
  <% end %>
<% end %>

app/views/users/_form.html.erb
<%= render "layouts/errors", :object => @user %>

<%= form_for(@user) do |f| %>
<div class="form-group">
  <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field  :password %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <%= f.submit(:class => "btn btn-primary") %>
<% end %>

app/views/users/index.html.erb
<h1> Welcome <%= current_user.email %> </h1>

<%= link_to "Upload Photos", new_user_photo_path(current_user) %>
<%= link_to "My Photos", user_path(current_user.id) %>
<%= link_to "Photos i'm tagged in", photo_tags_path(current_user.id) %>

<% current_user.photos.uniq.each do |photo| %>
<div style="text-align:center">
  <p ><%= image_tag photo.image.url(:medium) %></p>


<% end %>
</br>
</div>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1>My Photos</h1>

<% Photo.all.each do |photo| %>
  <% if photo.user_id == @user.id %>

  <div class="grey">
    <p><%=link_to image_tag(photo.image.url(:medium)), new_photo_tag_path(photo) %></p>



  </div>
  <% end %>
<% end %>




<p><%= link_to "Add a new photo", new_user_photo_path(current_user) %>